server:
  port: 8005
eureka:
  instance:
    hostname: localhost
  client: #in production we keep them as enabled as it runs multiple eureka servers
    registerWithEureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8005/eureka/